dic = {"avg_npersons": "Average number of families in a household",
    "avg_room_num" : "Average number of rooms available to members of households for sleeping",
    "perc_rural" : "Percentage of rural households",
    "unrel_ppl" : "Average number of people in a household that are unrelated to the head of the household",
    "perc_owned" : "Percentage of population owning their home",
    "perc_yes_electricity" : "Percentage of population access to electricity ",
    "perc_piped_inside_dwelling" : "Percentage of population with water piped inside dwelling",
    "perc_piped_within_building" : "Percentage of population with water piped within the building or plot of land",
    "perc_no_piped_water" : "Percentage of population with no piped water",
    "perc_sewage_system" : "Percentage of population with access to sewage system (public sewage disposal)",
    "perc_septic_tank" : "Percentage of population with access to septic tank (private sewage disposal)",
    "perc_no_sewage_system" : "Percentage of population not connected to sewage disposal system",
    "perc_no_fuelcook" : "Percentage of population with no cooking fuel",
    "perc_electricity_fuelcook" : "Percentage of population using electricity as cooking fuel",
    "perc_petroleum_gas_fuelcook" : "Percentage of population using petroleum gas, unspecified as cooking fuel",
    "perc_wood_charcoal_fuelcook" : "Percentage of population using wood or charcoal cooking fuel",
    "perc_yes_phone" : "Percentage of population with access to a telephone",
    "perc_yes_cell" : "Percentage of population with access to a cellphone",
    "perc_yes_internet" : "Percentage of population with access to the internet",
    "perc_trash_directly_collected_from_household" : "Percentage of population with trash collected directly from the household or dwelling",
    "perc_trash_communal_refuse_dump" : "Percentage of population using a communal refuse dump for trash",
    "perc_yes_autos" : "Percentage of population with an automobile",
    "perc_yes_hotwater" : "Percentage of population with access to hotwater",
    "perc_yes_aircon" : "Percentage of population with air conditioning",
    "perc_yes_computer" : "Percentage of population with access to a computer",
    "perc_yes_washer" : "Percentage of population with access to washer",
    "perc_yes_refrig" : "Percentage of population with access to refrig",
    "perc_yes_atleastone_tv" : "Percentage of population with at least one color T.V.",
    "perc_yes_radio" : "Percentage of population access to radio",
    "perc_yes_kitchen" : "Percentage of population with a kitchen",
    "perc_flush_toilet" : "Percentage of population with a flush toilet",
    "perc_non_flush_latrine" : "Percentage of population with a non-flush, latrine toilet",
    "perc_yes_bath" : "Percentage of population with a bathroom",
    "perc_no_unfinished_floor" : "Percentage of population with an unfinished (earth) floor",
    "perc_cement_floor" : "Percentage of population with a cement floor",
    "perc_scrap_wall" : "Percentage of population with a waste, scrap, or discarded material wall",
    "perc_cardboard_wall" : "Percentage of population with a cardboard sheet wall",
    "perc_wood_wall" : "Percentage of population with a wood wall",
    "perc_reed_bamboo_palm_wall" : "Percentage of population with a reed, bamboo, or palm wall",
    "perc_brick_stone_wall" : "Percentage of population with a brick, block, stone, or cement wall",
    "perc_adobe_wall" : "Percentage of population with a adobe wall",
    "perc_mud_wall" : "Percentage of population with a mud or adobe wall",
    "perc_metal_asbestos_sheet_wall" : "Percentage of population with a metal or asbestos sheet wall",
    "perc_masonry_roof" : "Percentage of population with a masonry, concrete, clay tile, or tiles of unspecified type roof",
    "perc_plastic_roof" : "Percentage of population with a fibercement or plastic roof",
    "perc_slate_roof" : "Percentage of population with a slate or tile roof",
    "perc_asbestos_roof" : "Percentage of population with a asbestos roof",
    "perc_sheet_metal_roof" : "Percentage of population with a sheet metal roof",
    "perc_plant_materials_roof" : "Percentage of population with a wood and other plant materials roof",
    "perc_wood_roof" : "Percentage of population with a wood roof",
    "perc_thatch_roof" : "Percentage of population with a thatch (straw, grass, leaves, palm, etc.) roof",
    "perc_scrap_material_roof" : "Percentage of population with a discarded or scrap material roof",
    "perc_cardboard_roof" : "Percentage of population with a cardboard roof",
    "perc_one_person_hhtype" : "Percentage of population with a one-person household",
    "perc_married_with_children_hhtype" : "Percentage of population living as a married/cohabitational couple with children",
    "perc_single_parent_hhtype" : "Percentage of population living as a single-parent family",
    "perc_extended_family_hhtype" : "Percentage of population living with extended family (relatives only)",
    "perc_composite_hhytpe" : "Percentage of population living with a composite household (family and non-relatives)",
    "perc_non_family_hhtype" : "Percentage of population living as a non-family household"}

print(dic.keys())